name: perplexity_flutter
description: A lightweight Flutter SDK to interact with Perplexity.ai's chat
  completion API (streaming + model switching supported).
version: 1.0.4
homepage: https://github.com/vishnu32510/perplexity_flutter
repository: https://github.com/vishnu32510/perplexity_flutter
issue_tracker: https://github.com/vishnu32510/perplexity_flutter/issues
topics:
  - perplexity
  - chat
  - ai
  - llm
  - sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
